# Generated by Django 4.1.4 on 2022-12-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileSubscriptions',
            new_name='Mobile',
        ),
    ]
